//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAngularJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualification
    {
        public int Qid { get; set; }
        public string type { get; set; }
    }
}
