//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAngularJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int StudentID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public string Qualification { get; set; }
        public string Role { get; set; }
        public string Tag { get; set; }
        public string color { get; set; }
        public string color2 { get; set; }
        public string Country { get; set; }
    }
}
